/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TortuvchilarRouteImport } from './routes/tortuvchilar'
import { Route as TopshiriqlarRouteImport } from './routes/topshiriqlar'
import { Route as SozlamalarRouteImport } from './routes/sozlamalar'
import { Route as MahsulotlarRouteImport } from './routes/mahsulotlar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IshchilarRouteImport } from './routes/ishchilar'
import { Route as HisobotRouteImport } from './routes/hisobot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TortuvchilarIndexRouteImport } from './routes/tortuvchilar.index'
import { Route as TortuvchilarWorkersRouteImport } from './routes/tortuvchilar.workers'
import { Route as TortuvchilarWorkerLoginRouteImport } from './routes/tortuvchilar.worker-login'
import { Route as TortuvchilarWorkerRouteImport } from './routes/tortuvchilar.worker'
import { Route as TortuvchilarSettingsRouteImport } from './routes/tortuvchilar.settings'
import { Route as TortuvchilarReportsRouteImport } from './routes/tortuvchilar.reports'
import { Route as TortuvchilarProductsRouteImport } from './routes/tortuvchilar.products'
import { Route as TortuvchilarLiveRouteImport } from './routes/tortuvchilar.live'
import { Route as TortuvchilarWorkerIndexRouteImport } from './routes/tortuvchilar.worker.index'
import { Route as TortuvchilarWorkerNewRouteImport } from './routes/tortuvchilar.worker.new'

const TortuvchilarRoute = TortuvchilarRouteImport.update({
  id: '/tortuvchilar',
  path: '/tortuvchilar',
  getParentRoute: () => rootRouteImport,
} as any)
const TopshiriqlarRoute = TopshiriqlarRouteImport.update({
  id: '/topshiriqlar',
  path: '/topshiriqlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlamalarRoute = SozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const MahsulotlarRoute = MahsulotlarRouteImport.update({
  id: '/mahsulotlar',
  path: '/mahsulotlar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IshchilarRoute = IshchilarRouteImport.update({
  id: '/ishchilar',
  path: '/ishchilar',
  getParentRoute: () => rootRouteImport,
} as any)
const HisobotRoute = HisobotRouteImport.update({
  id: '/hisobot',
  path: '/hisobot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TortuvchilarIndexRoute = TortuvchilarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarWorkersRoute = TortuvchilarWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarWorkerLoginRoute = TortuvchilarWorkerLoginRouteImport.update({
  id: '/worker-login',
  path: '/worker-login',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarWorkerRoute = TortuvchilarWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarSettingsRoute = TortuvchilarSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarReportsRoute = TortuvchilarReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarProductsRoute = TortuvchilarProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarLiveRoute = TortuvchilarLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => TortuvchilarRoute,
} as any)
const TortuvchilarWorkerIndexRoute = TortuvchilarWorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TortuvchilarWorkerRoute,
} as any)
const TortuvchilarWorkerNewRoute = TortuvchilarWorkerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TortuvchilarWorkerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hisobot': typeof HisobotRoute
  '/ishchilar': typeof IshchilarRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/tortuvchilar': typeof TortuvchilarRouteWithChildren
  '/tortuvchilar/live': typeof TortuvchilarLiveRoute
  '/tortuvchilar/products': typeof TortuvchilarProductsRoute
  '/tortuvchilar/reports': typeof TortuvchilarReportsRoute
  '/tortuvchilar/settings': typeof TortuvchilarSettingsRoute
  '/tortuvchilar/worker': typeof TortuvchilarWorkerRouteWithChildren
  '/tortuvchilar/worker-login': typeof TortuvchilarWorkerLoginRoute
  '/tortuvchilar/workers': typeof TortuvchilarWorkersRoute
  '/tortuvchilar/': typeof TortuvchilarIndexRoute
  '/tortuvchilar/worker/new': typeof TortuvchilarWorkerNewRoute
  '/tortuvchilar/worker/': typeof TortuvchilarWorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hisobot': typeof HisobotRoute
  '/ishchilar': typeof IshchilarRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/tortuvchilar/live': typeof TortuvchilarLiveRoute
  '/tortuvchilar/products': typeof TortuvchilarProductsRoute
  '/tortuvchilar/reports': typeof TortuvchilarReportsRoute
  '/tortuvchilar/settings': typeof TortuvchilarSettingsRoute
  '/tortuvchilar/worker-login': typeof TortuvchilarWorkerLoginRoute
  '/tortuvchilar/workers': typeof TortuvchilarWorkersRoute
  '/tortuvchilar': typeof TortuvchilarIndexRoute
  '/tortuvchilar/worker/new': typeof TortuvchilarWorkerNewRoute
  '/tortuvchilar/worker': typeof TortuvchilarWorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hisobot': typeof HisobotRoute
  '/ishchilar': typeof IshchilarRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/tortuvchilar': typeof TortuvchilarRouteWithChildren
  '/tortuvchilar/live': typeof TortuvchilarLiveRoute
  '/tortuvchilar/products': typeof TortuvchilarProductsRoute
  '/tortuvchilar/reports': typeof TortuvchilarReportsRoute
  '/tortuvchilar/settings': typeof TortuvchilarSettingsRoute
  '/tortuvchilar/worker': typeof TortuvchilarWorkerRouteWithChildren
  '/tortuvchilar/worker-login': typeof TortuvchilarWorkerLoginRoute
  '/tortuvchilar/workers': typeof TortuvchilarWorkersRoute
  '/tortuvchilar/': typeof TortuvchilarIndexRoute
  '/tortuvchilar/worker/new': typeof TortuvchilarWorkerNewRoute
  '/tortuvchilar/worker/': typeof TortuvchilarWorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hisobot'
    | '/ishchilar'
    | '/login'
    | '/mahsulotlar'
    | '/sozlamalar'
    | '/topshiriqlar'
    | '/tortuvchilar'
    | '/tortuvchilar/live'
    | '/tortuvchilar/products'
    | '/tortuvchilar/reports'
    | '/tortuvchilar/settings'
    | '/tortuvchilar/worker'
    | '/tortuvchilar/worker-login'
    | '/tortuvchilar/workers'
    | '/tortuvchilar/'
    | '/tortuvchilar/worker/new'
    | '/tortuvchilar/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hisobot'
    | '/ishchilar'
    | '/login'
    | '/mahsulotlar'
    | '/sozlamalar'
    | '/topshiriqlar'
    | '/tortuvchilar/live'
    | '/tortuvchilar/products'
    | '/tortuvchilar/reports'
    | '/tortuvchilar/settings'
    | '/tortuvchilar/worker-login'
    | '/tortuvchilar/workers'
    | '/tortuvchilar'
    | '/tortuvchilar/worker/new'
    | '/tortuvchilar/worker'
  id:
    | '__root__'
    | '/'
    | '/hisobot'
    | '/ishchilar'
    | '/login'
    | '/mahsulotlar'
    | '/sozlamalar'
    | '/topshiriqlar'
    | '/tortuvchilar'
    | '/tortuvchilar/live'
    | '/tortuvchilar/products'
    | '/tortuvchilar/reports'
    | '/tortuvchilar/settings'
    | '/tortuvchilar/worker'
    | '/tortuvchilar/worker-login'
    | '/tortuvchilar/workers'
    | '/tortuvchilar/'
    | '/tortuvchilar/worker/new'
    | '/tortuvchilar/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HisobotRoute: typeof HisobotRoute
  IshchilarRoute: typeof IshchilarRoute
  LoginRoute: typeof LoginRoute
  MahsulotlarRoute: typeof MahsulotlarRoute
  SozlamalarRoute: typeof SozlamalarRoute
  TopshiriqlarRoute: typeof TopshiriqlarRoute
  TortuvchilarRoute: typeof TortuvchilarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tortuvchilar': {
      id: '/tortuvchilar'
      path: '/tortuvchilar'
      fullPath: '/tortuvchilar'
      preLoaderRoute: typeof TortuvchilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topshiriqlar': {
      id: '/topshiriqlar'
      path: '/topshiriqlar'
      fullPath: '/topshiriqlar'
      preLoaderRoute: typeof TopshiriqlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlamalar': {
      id: '/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof SozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahsulotlar': {
      id: '/mahsulotlar'
      path: '/mahsulotlar'
      fullPath: '/mahsulotlar'
      preLoaderRoute: typeof MahsulotlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ishchilar': {
      id: '/ishchilar'
      path: '/ishchilar'
      fullPath: '/ishchilar'
      preLoaderRoute: typeof IshchilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisobot': {
      id: '/hisobot'
      path: '/hisobot'
      fullPath: '/hisobot'
      preLoaderRoute: typeof HisobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tortuvchilar/': {
      id: '/tortuvchilar/'
      path: '/'
      fullPath: '/tortuvchilar/'
      preLoaderRoute: typeof TortuvchilarIndexRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/workers': {
      id: '/tortuvchilar/workers'
      path: '/workers'
      fullPath: '/tortuvchilar/workers'
      preLoaderRoute: typeof TortuvchilarWorkersRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/worker-login': {
      id: '/tortuvchilar/worker-login'
      path: '/worker-login'
      fullPath: '/tortuvchilar/worker-login'
      preLoaderRoute: typeof TortuvchilarWorkerLoginRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/worker': {
      id: '/tortuvchilar/worker'
      path: '/worker'
      fullPath: '/tortuvchilar/worker'
      preLoaderRoute: typeof TortuvchilarWorkerRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/settings': {
      id: '/tortuvchilar/settings'
      path: '/settings'
      fullPath: '/tortuvchilar/settings'
      preLoaderRoute: typeof TortuvchilarSettingsRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/reports': {
      id: '/tortuvchilar/reports'
      path: '/reports'
      fullPath: '/tortuvchilar/reports'
      preLoaderRoute: typeof TortuvchilarReportsRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/products': {
      id: '/tortuvchilar/products'
      path: '/products'
      fullPath: '/tortuvchilar/products'
      preLoaderRoute: typeof TortuvchilarProductsRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/live': {
      id: '/tortuvchilar/live'
      path: '/live'
      fullPath: '/tortuvchilar/live'
      preLoaderRoute: typeof TortuvchilarLiveRouteImport
      parentRoute: typeof TortuvchilarRoute
    }
    '/tortuvchilar/worker/': {
      id: '/tortuvchilar/worker/'
      path: '/'
      fullPath: '/tortuvchilar/worker/'
      preLoaderRoute: typeof TortuvchilarWorkerIndexRouteImport
      parentRoute: typeof TortuvchilarWorkerRoute
    }
    '/tortuvchilar/worker/new': {
      id: '/tortuvchilar/worker/new'
      path: '/new'
      fullPath: '/tortuvchilar/worker/new'
      preLoaderRoute: typeof TortuvchilarWorkerNewRouteImport
      parentRoute: typeof TortuvchilarWorkerRoute
    }
  }
}

interface TortuvchilarWorkerRouteChildren {
  TortuvchilarWorkerNewRoute: typeof TortuvchilarWorkerNewRoute
  TortuvchilarWorkerIndexRoute: typeof TortuvchilarWorkerIndexRoute
}

const TortuvchilarWorkerRouteChildren: TortuvchilarWorkerRouteChildren = {
  TortuvchilarWorkerNewRoute: TortuvchilarWorkerNewRoute,
  TortuvchilarWorkerIndexRoute: TortuvchilarWorkerIndexRoute,
}

const TortuvchilarWorkerRouteWithChildren =
  TortuvchilarWorkerRoute._addFileChildren(TortuvchilarWorkerRouteChildren)

interface TortuvchilarRouteChildren {
  TortuvchilarLiveRoute: typeof TortuvchilarLiveRoute
  TortuvchilarProductsRoute: typeof TortuvchilarProductsRoute
  TortuvchilarReportsRoute: typeof TortuvchilarReportsRoute
  TortuvchilarSettingsRoute: typeof TortuvchilarSettingsRoute
  TortuvchilarWorkerRoute: typeof TortuvchilarWorkerRouteWithChildren
  TortuvchilarWorkerLoginRoute: typeof TortuvchilarWorkerLoginRoute
  TortuvchilarWorkersRoute: typeof TortuvchilarWorkersRoute
  TortuvchilarIndexRoute: typeof TortuvchilarIndexRoute
}

const TortuvchilarRouteChildren: TortuvchilarRouteChildren = {
  TortuvchilarLiveRoute: TortuvchilarLiveRoute,
  TortuvchilarProductsRoute: TortuvchilarProductsRoute,
  TortuvchilarReportsRoute: TortuvchilarReportsRoute,
  TortuvchilarSettingsRoute: TortuvchilarSettingsRoute,
  TortuvchilarWorkerRoute: TortuvchilarWorkerRouteWithChildren,
  TortuvchilarWorkerLoginRoute: TortuvchilarWorkerLoginRoute,
  TortuvchilarWorkersRoute: TortuvchilarWorkersRoute,
  TortuvchilarIndexRoute: TortuvchilarIndexRoute,
}

const TortuvchilarRouteWithChildren = TortuvchilarRoute._addFileChildren(
  TortuvchilarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HisobotRoute: HisobotRoute,
  IshchilarRoute: IshchilarRoute,
  LoginRoute: LoginRoute,
  MahsulotlarRoute: MahsulotlarRoute,
  SozlamalarRoute: SozlamalarRoute,
  TopshiriqlarRoute: TopshiriqlarRoute,
  TortuvchilarRoute: TortuvchilarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
